### ISSUE TITLE
Date Picker is not working in IE and FireFox

### ISSUE THREAD

**Issue by pushkar4you** [zebzhao/Angular-QueryBuilder#4]
Hi,

I have integrated QueryBuilder in my Angular 4 project. My project supporting browser is IE and FireFox only. QueryBuilder works very well but I found only one major issue. If my RULE is date field then field doesn't show date picker in IE and FireFox. I know in QueryBuilder we are using HTML5 date picker which is officially not supported in IE and FireFox yet but anybody knows any workaround for this issue.

Please please provide any solution or advise.

Thanks,
Pushkar

**Comment by zebzhao** [comment]
Hi, sorry I haven't been working on this project as I been quite busy lately. I would fork the project and change the HTML template to integrate your own custom components. Since the components are decided by `type` field on the configuration, you can add custom `type` to indicate custom components.

I've been always planning to implement something similar to material table in query builder where you can transclude some custom components. I think its better illustrated with an example:

`
<query-builder>
  <ng-container rule-type="customDatepicker">
    <custom-datepicker></custom-datepicker>
  </ng-container>
</query-builder>
`

In the configuration it would look something like this:

{
  "condition": "and",
  "rules": [
    {
      "field": "age",
      "type": "customDatepicker",
      "getOperators": function () {
        return ['=', '!=', '>', '>=', '<', '<='];
      }
    }
}

Let me know your thoughts on this.

**Comment by zebzhao** [comment]
e017ca47c7a8261d626eb7b7c8d68d0b955c81aa
